server.port=8081


spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/coworking
spring.datasource.username=root
spring.datasource.password=localhost

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


logging.level.org.hibernate.SQL=warn
springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=5E9CF4C3B6A8D2F1A9E2C7D8B1A4E6F3
security.jwt.exp-min=120
